name: Theme Cards Unit Test

on: [push]

jobs: 
  build: 

    runs-on: ubuntu-latest

    steps: 

      - name: Node.js envs
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
          
      - name: Generate
        run: |
          npm install hexo-cli --global
          git clone https://github.com/ChrAlpha/hexo-theme-cards-unit-test test
          cd test
          git clone https://github.com/ChrAlpha/hexo-theme-cards themes/cards
          npm install
          hexo clean && hexo generate